### ISSUE TITLE
"X out of Y words typed" message needs to be more friendly

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/anti-slavery-manuscripts#149]
## UI/UX Improvement Needed
As @beckyrother pointed out, the glaring red "X out of Y words typed" message looks rather hostile to users, especially when a user first starts transcribing. (It's 0 out of Y words, and loos like an error message is occurring before the user even has a chance to start.)
![screen shot 2017-11-06 at 19 02 09](https://user-images.githubusercontent.com/13952701/32458665-0c7a5ca0-c325-11e7-9f6a-9c34c420340f.png)

### Recommended Changes
- For starters, ditch the red (i.e. negative feedback) visuals.
- Instead, use the following feedback/messaging system:
  - [ ] If words !== dots-1, display _"X out of Y words typed"_ in _neutral colours._
  - [ ] If words === dots-1, display _"Y out of Y words typed 👍 "_ in _approval/good colours,_ and maybe with a 👍  icon to indicate they've done everything that's expected.
  - [ ] If input.contains('[tags]'), display _"X out of Y words typed. However, we noticed you added insertion/deletion/unclear tags, so don't worry too much about the word count. If you want to know more about how to handle weird insertion/deletion cases, [click here](https://giphy.com/gifs/idk-shrug-power-rangers-y65VoOlimZaus) "_
- Allow users to submit data EVEN if words don't match number of dots. Observe the following possibilities:
  - [ ] When the user hits Done/Done & Talk, AND words === dots-1, proceed normally.
  - [ ] When the user hits Done/Done & Talk, AND words !== dots-1, prompt the user with a confirmation dialogue: _"We expected you to type Y words since you marked Y+1 dots, but you typed in X words. Are you sure you're done? Yes/No"_
  - [ ] When the user hits Done/Done & Talk, AND words !== dots-1 AND [tags] detected, prompt the user with a confirmation dialogue: _"[insertion][deletion] can be pretty tricky and can mess up the expected word count. You can check [our guide](https://giphy.com/gifs/idk-shrug-power-rangers-y65VoOlimZaus) if you're unsure, but if you're confident, we can proceed. Done? Yes/No"_

### Status
Priority TBC, and the text copy needs some attention, but I'd like to see this running for Beta since it ties in with the other "what to do with [insertion] [deletion]" issue/implementation discussion.

**Comment by beckyrother** [comment]
Thanks Shaun! I like where this is going. Couple comments about the first solution:

- I'm imagining the feedback/count to be something like the way Twitter treats its character count: very subtle, in the bottom right corner, and only turns red after an error: 
![_1__twitter](https://user-images.githubusercontent.com/1392130/32462731-0db2ec1a-c300-11e7-9c6f-e16b64ea69bd.png)
![_2__twitter](https://user-images.githubusercontent.com/1392130/32462732-0dc032a8-c300-11e7-979d-a98ff0fb563f.png)

- Maybe if an `insertion` tag is present the number goes negative but does not turn red to indicate that it's not an error. A `?` button next to the number can explain: "_The number of words you type should be 1 fewer than the number of buttons you placed. Insertion/deletion tags do not affect this count. Learn more_"


I like the first solution better than the second, since users in the design survey I sent out a few months ago almost universally complained about the number of clicks between tasks in the classifier. The fewer the clicks, the more the engagement.

**Comment by CKrawczyk** [comment]
I just want to point out if the number of words !== number of dots -1 the extractor will *not* use the classification at all.  If this is allowed on the front end it would require major updates to the extractor/reducer.
