### ISSUE TITLE
Confusion regarding [insertion] and [deletion]

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/anti-slavery-manuscripts#150]
## Implementation Discussion Required
Say we have a line of text where an 'inserted' but of text appears _visually above_ a deletion/struck-out word.
```
                   land                        the midnight sun
We come from the --^-- of the ice and snow, from --^--, where the hot springs flow
```

How is this supposed to look like? Are those three lines of Annotation, one for `"land"` , one for `"the midnight sun"` , one for `"We come from the [deletion][unclear][/deletion] of the ice and snow, from [deletion][unclear][/deletion], where the hot springs flow"` ? (Which will cause havoc with the final data export for the library?)

Or will it be a single line that somehow looks like `"We come from the [deletion][unclear][/deletion] [insertion]land[/insertion] of the ice and snow, from [deletion][unclear][/deletion] [insertion]the midnight sun[/insertion], where the hot springs flow"` ? (Which will cause havoc with the aggregation system?)

However we choose to look at this (not-so-)edge case, our implementation might cause a lot of confusion for how users are expected to Annotate that line, given that...
1. We use segmented lines, assuming that all words are in a more-or-less straight line. (i.e. doesn't account for the 'insertion word' being 'above' the main line of text.)
2. We use word counts to prevent nonsensical data from being sent to our aggregation engine. (Insertion/deletions of this nature aren't really accounted for in all our logic checks)

So, what do we need to do? [Click here for the detailed answer.](https://giphy.com/gifs/idk-shrug-power-rangers-y65VoOlimZaus)

### Notes
Be aware that any word count logic changes might/will very likely run into any changes we make in PR #149 

### Status
Discussion needed; priority TBC.

**Comment by CKrawczyk** [comment]
I want to put my vote in for three annotated lines of the form:
`We come from the [deletion][unclear][/deletion] of the ice and snow, from [deletion][unclear][/deletion], where the hot springs flow`
`[insertion]land[/insertion]`
`[insertion]the midnight sun[/insertion]`

The tag information and the spatial information from the dots should allow for a (post processing) reconstruction of the text on the page.

Otherwise there are words without spatial information (no dots) making a page reconstruction impossible from the classifications alone.

**Comment by wgranger** [comment]
I'm closing this issue as it appears we have been following through with a working solution.
