### ISSUE TITLE
Seven-ten Isn't Logging in IE

### ISSUE THREAD

**Issue by wgranger** [zooniverse/anti-slavery-manuscripts#214]
IE has a problem with the `Split.classificationCreated` function, and a temporary fix was found in #212. However, we need this function to log seven-ten classifications in the project. Before full launch, a fix should be found.

**Comment by shaunanoordin** [comment]
Given the granularity of the error, I need to check if
1. do the other Split.* functions work in IE11?
2. does Split.classificationCreated even work on a simple page, say we create localhost:3000/test that does nothing BUT do Split.classificationCreated with a test Classification object?
3. What I said about 2, but using null as the test object?

Basically, I want to check whether the issue is within SevenTen itself not being compatible with IE11, or whether we borked with our object argument. It may be the first thing, and if so... who'd know how to fix it?

EDIT: Just a thought, does SevenTen run polyfills?

**Comment by srallen** [comment]
The bundled main.js file should be polyfilled by the polyfill service loaded which would include the Seven-Ten client. Try adding es6 to the list of features that is polyfilled by the polyfill service here: https://github.com/zooniverse/anti-slavery-manuscripts/blob/master/src/index.tpl.html#L7 (see PFE's setup: https://github.com/zooniverse/Panoptes-Front-End/blob/master/views/index.ejs#L73

I'd also recommend moving that script tag out of the head and into the bottom of the body for performance reasons. 

My guess is that the for...of loop isn't getting polyfilled correctly and IE doesn't support that: https://github.com/zooniverse/Seven-Ten-Client/blob/master/src/split.js#L34
