### ISSUE TITLE
Build the Crib Sheet

### ISSUE THREAD

**Issue by wgranger** [zooniverse/anti-slavery-manuscripts#9]
At present, some more thought needs to go into exactly how this will function. This crib sheet will display information from past classifications to aid the volunteer in annotations.

**Comment by shaunanoordin** [comment]
As of 12 June 2017, we have not yet fully decided on the feature specs for Liberating the Liberator's Crib Sheets feature, but we have some baseline ideas.

* The original cribsheet system (used in Shakespeare's World) had to goals:
  * provide the user a _personal_ "visual reference" collection
  * provide some undocumented future 'sharing/collaboration' functionality (that ultimately wasn't implemented)
* Our new crib sheet will work off the original, but perhaps with more emphasis on the sharing/collaboration feature.
  * For example, we may want to have cribsheets associated by subject instead of by user (ref: Slack, #imls channel, 1 June 2017)
  * Alternatively, we may want to allow cribsheets to be shared on Talk.
* For reference on how the cribsheets currently work:
![imls-cribsheet-study-20170601](https://user-images.githubusercontent.com/13952701/27038653-84c43dc2-4f83-11e7-95ad-eed3c63b013c.png)
_Transcription Project Cribsheets: A quick guide on how they currently work (on Shakespeare's World)_
